version: "3.7"
services:
  app:
    build:
      args:
        user: develop
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: php8_development
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - sites_network

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - sites_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - sites_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - sites_network

networks:
  sites_network:
    driver: bridge
